In [1]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3]

In [3]:
minha_lista

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

In [5]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
arr = np.zeros(3)

In [11]:
arr

array([0., 0., 0.])

In [13]:
arr = np.zeros((5, 5))

In [14]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [22]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [23]:
np.random.rand(5)

array([0.32780932, 0.80003669, 0.13071149, 0.22666534, 0.95440832])

In [24]:
np.random.randn(4)

array([-0.5087434 , -0.43516111, -0.87820655,  1.11431184])

In [25]:
np.random.randint(0, 100, 10)

array([17, 71, 20, 38, 53, 85, 31, 78, 37, 99])

In [26]:
arr = np.random.rand(25)

In [27]:
arr

array([0.6974941 , 0.96902309, 0.81363581, 0.66436645, 0.96085313,
       0.64503229, 0.36412091, 0.86888791, 0.1838113 , 0.1301965 ,
       0.89800082, 0.29464171, 0.20602148, 0.03443997, 0.89793354,
       0.38142404, 0.15111097, 0.55353066, 0.94111463, 0.07444733,
       0.3064387 , 0.09736974, 0.86445791, 0.51360144, 0.27223513])

In [30]:
arr.reshape((5,5))

array([[0.6974941 , 0.96902309, 0.81363581, 0.66436645, 0.96085313],
       [0.64503229, 0.36412091, 0.86888791, 0.1838113 , 0.1301965 ],
       [0.89800082, 0.29464171, 0.20602148, 0.03443997, 0.89793354],
       [0.38142404, 0.15111097, 0.55353066, 0.94111463, 0.07444733],
       [0.3064387 , 0.09736974, 0.86445791, 0.51360144, 0.27223513]])

In [31]:
arr.max()

np.float64(0.9690230907118846)

In [32]:
arr.min()

np.float64(0.03443996959215745)

In [33]:
arr.argmax()

np.int64(1)

In [34]:
arr.argmin()

np.int64(13)