In [1]:
# Importação da biblioteca
import numpy as np

In [2]:
# define um array de 0 a 30 de passo 3
arr = np.arange(0, 30, 3)

In [3]:
# mostra o array
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
# acessa a posição 3 do array
arr[3]

np.int64(9)

In [5]:
# cria uma slice do elemento 2 ate o 4
arr[2:5]

array([ 6,  9, 12])

In [7]:
# 5 primeiros numeros
arr[:5]

array([ 0,  3,  6,  9, 12])

In [8]:
# todos menos os 2 primeiros
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [9]:
# atribuição de todas as posiçoes para 100 (menos as 2 primeiras)
arr[2:] = 100

In [10]:
# mostra o array
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [11]:
# gera um array 1x50 de numeros de 1 a 50 e reorganiza em um array 5x10
arr = np.arange(50).reshape((5, 10))

In [12]:
# mostra o array gerado acima
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [13]:
# mostra o shape da estrutura (5x10)
arr.shape

(5, 10)

In [15]:
# cria uma referencia as 2 primeiros elementos do array (no caso 2 linhas)
arr2 = arr[:2]

In [17]:
# atribui 100 a essas linhas
arr2[:] = 100

In [18]:
# array alterado
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [19]:
# por ser referencia altera o original
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [20]:
# gera uma cópia na mnemoria (nao só um ponteiro)
arr2 = arr[:2].copy()

In [23]:
# gera slices das linhas e colunas (das posições, 1 a 3 e 5 em diante)
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [ 25,  26,  27,  28,  29],
       [ 35,  36,  37,  38,  39]])

In [1]:
# array booleano (1 para as posições q a operação retorna true)
bol = arr > 50

NameError: name 'arr' is not defined

In [25]:
# array booleano utilizazdo como indice
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [26]:
# gera 30 numeros igualmente espaçados de 0 a 100
arr = np.linspace(0, 100, 30)

In [27]:
# mostra o shape da estrutura (1x30)
arr.shape()

(30,)

In [29]:
# altera o shape para 3x10
arr = arr.reshape(3, 10)

In [30]:
# slice das linhas 0 1 mostrando a coluna 2
arr[0:2, 2]

array([ 6.89655172, 41.37931034])