In [1]:
# importação da biblioteca 
import numpy as np

In [2]:
# criando uma lista
minha_lista = [1, 2, 3]

In [3]:
# mostrando a lista
minha_lista

[1, 2, 3]

In [4]:
# criando array np
np.array(minha_lista)

array([1, 2, 3])

In [5]:
# lista de listas (aka matriz)
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [1]:
# matriz numpy (array 2D)
np.array(minha_matriz)

NameError: name 'np' is not defined

In [7]:
# gerando sequencia de 0 a 10 (analogo ao range(), mas gera um array ao inves de lista)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# array de 0 a 10 com passo de 2 (2 em 2 numeros)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
# array de zeros
np.zeros(3)

array([0., 0., 0.])

In [10]:
# array de zeros
arr = np.zeros(3)

In [11]:
# mostra array de zeros
arr

array([0., 0., 0.])

In [13]:
# atribuição de uma matriz 5x5 de zeros
arr = np.zeros((5, 5))

In [14]:
# mostra a matriz 5x5
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# gera uma matriz de 1's 3x3
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# gera uma identidade (matriz de 0's com coluna de 1's) 4x4 (sempre quadrada)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# gera um array com 2 numeros igualmente espaçados de 0 a 10
np.linspace(0, 10, 2)

array([ 0., 10.])

In [22]:
# gera um array com 3 numeros igualmente espaçados de 0 a 10
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [23]:
# gera um array de numeros aleatorios de 0 a 1 com 5 posições
np.random.rand(5)

array([0.32780932, 0.80003669, 0.13071149, 0.22666534, 0.95440832])

In [24]:
# um array com 4 posições de numeros de uma distribuição normal

np.random.randn(4)

array([-0.5087434 , -0.43516111, -0.87820655,  1.11431184])

In [25]:
# 10 numeros inteiros aleatorios de 0 a 100
np.random.randint(0, 100, 10)

array([17, 71, 20, 38, 53, 85, 31, 78, 37, 99])

In [26]:
# atribuição de um array com 25 numeros aleatorios
arr = np.random.rand(25)

In [27]:
# mostra o array
arr

array([0.6974941 , 0.96902309, 0.81363581, 0.66436645, 0.96085313,
       0.64503229, 0.36412091, 0.86888791, 0.1838113 , 0.1301965 ,
       0.89800082, 0.29464171, 0.20602148, 0.03443997, 0.89793354,
       0.38142404, 0.15111097, 0.55353066, 0.94111463, 0.07444733,
       0.3064387 , 0.09736974, 0.86445791, 0.51360144, 0.27223513])

In [30]:
# redefine o array 1x25 para um 5x5
arr.reshape((5,5))

array([[0.6974941 , 0.96902309, 0.81363581, 0.66436645, 0.96085313],
       [0.64503229, 0.36412091, 0.86888791, 0.1838113 , 0.1301965 ],
       [0.89800082, 0.29464171, 0.20602148, 0.03443997, 0.89793354],
       [0.38142404, 0.15111097, 0.55353066, 0.94111463, 0.07444733],
       [0.3064387 , 0.09736974, 0.86445791, 0.51360144, 0.27223513]])

In [31]:
# maior numero do array
arr.max()

np.float64(0.9690230907118846)

In [32]:
# menor numero do array
arr.min()

np.float64(0.03443996959215745)

In [33]:
#posição do maior numero
arr.argmax()

np.int64(1)

In [34]:
#posição do menor numero
arr.argmin()

np.int64(13)