# Validação Cruzada
Consiste em separar o conjunto de dados em k divisões e realizar k treinos, sempre alterando a divisão para teste, sendo assim utilizando todos os dados para treinamento (evitando que dados importantes possam ficar apenas no conjunto de treino)

In [45]:
# import das bibliotecas
import pandas as pd
import tensorflow as tf
import sklearn
import scikeras

In [46]:
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras import backend as k
from sklearn.model_selection import GridSearchCV

In [33]:
# Importação da base de dados
X = pd.read_csv('/content/entradas_breast.csv')
y = pd.read_csv('/content/saidas_breast.csv')

In [ ]:
def criar_rede():
  # Limpa a sessão do tenserflow (libera os recursos, evitando overflow)
  k.clear_session()
  # Cria a rede como visto nas aulas anteriores (4 camadas, 2 ocultas)
  rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')])
  # Parametros do otimizador
  otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue=0.5)
  # Compila tudo e retorna a rede
  rede_neural.compile(optimizer=otimizador, loss='binary_crossentropy', metrics=['binary_accuracy'])
  return rede_neural

In [ ]:
# Cria o classificador
rede_neural = KerasClassifier(model=criar_rede, epochs=100, batch_size=10)

In [ ]:
# Realiza a cross validation, com 10 divisões
resultados = cross_val_score(estimator=rede_neural, X=X, y=y, cv=10, scoring='accuracy')

Epoch 1/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - binary_accuracy: 0.6304 - loss: 0.7034
Epoch 2/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7333 - loss: 0.4897
Epoch 3/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7712 - loss: 0.4704
Epoch 4/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8519 - loss: 0.4043
Epoch 5/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8048 - loss: 0.4543
Epoch 6/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8169 - loss: 0.4574
Epoch 7/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8230 - loss: 0.4818
Epoch 8/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8561 - loss: 0.3962
Epoch 9/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8552 - loss: 0.3845
Epoch 10/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8007 - loss: 0.5059
Epoch 11/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8191 -

In [ ]:
# Acertos de cada divisão
resultados

array([0.75438596, 0.77192982, 0.85964912, 0.89473684, 0.66666667,
       0.77192982, 0.87719298, 0.77192982, 0.85964912, 0.82142857])

In [ ]:
# Media dos acertos
resultados.mean()

0.8049498746867167

In [ ]:
# Desvio padrao
resultados.std()

0.06669801706002548

## Pratica

In [ ]:
# Senti uma melhora quando diminui as epocas e aumentei os batch_sizes
rede_neural = KerasClassifier(model=criar_rede, epochs=20, batch_size=70)

resultados = cross_val_score(estimator=rede_neural, X=X, y=y, cv=10, scoring='accuracy')

Epoch 1/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - binary_accuracy: 0.6110 - loss: 3.5312
Epoch 2/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.5622 - loss: 0.6403 
Epoch 3/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6068 - loss: 0.5953 
Epoch 4/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6624 - loss: 0.5260 
Epoch 5/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6645 - loss: 0.5101 
Epoch 6/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6754 - loss: 0.4723 
Epoch 7/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6606 - loss: 0.4623 
Epoch 8/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7212 - loss: 0.4684 
Epoch 9/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7961 - loss: 0.4574 
Epoch 10/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6793 - loss: 0.4616 
Epoch 11/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8374 - loss: 0.4190 
Epoch 12/

In [ ]:
resultados

array([0.85964912, 0.80701754, 0.89473684, 0.87719298, 0.84210526,
       0.92982456, 0.80701754, 0.9122807 , 0.75438596, 0.89285714])

In [ ]:
# Aparentemente funcionou
resultados.mean()

0.8577067669172932

In [ ]:
resultados.std()

0.052179441449306654

# Underfitting e Overfitting
- Quando o algoritmo se adapta muito ou pouco para dado problema.
- Matar uma mosca com uma bazuca e um dinossauro com uma raquete

## Underfitting
- Resultados ruins na base de treinamento

## Overfitting
- Resultados bons na base de treinamento
- Resultados ruins na base de teste
- Muito especifico
- Se adaptou demais aos dados de treinamento
- Novas variações geram erros

## Dropout
- Remover neuronios da rede
- Uma possivel solução para o overfitting
- Valores para dropar (de 20% a 30%)

In [ ]:
def criar_rede():
  # Limpa a sessão do tenserflow (libera os recursos, evitando overflow)
  k.clear_session()
  # Cria a rede como visto nas aulas anteriores (4 camadas, 2 ocultas)
  rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    # Nas camadas ocultas, realiza o dropout de 20% dos neuronios
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')])
  # Parametros do otimizador
  otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue=0.5)
  # Compila tudo e retorna a rede
  rede_neural.compile(optimizer=otimizador, loss='binary_crossentropy', metrics=['binary_accuracy'])
  return rede_neural

In [ ]:
# Cria o classificador
rede_neural = KerasClassifier(model=criar_rede, epochs=100, batch_size=10)

In [ ]:
# Realiza a cross validation, com 10 divisões
resultados = cross_val_score(estimator=rede_neural, X=X, y=y, cv=10, scoring='accuracy')

Epoch 1/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - binary_accuracy: 0.5310 - loss: 3.9155
Epoch 2/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6399 - loss: 0.7023
Epoch 3/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7126 - loss: 0.6657
Epoch 4/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6595 - loss: 0.7712
Epoch 5/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6551 - loss: 0.5985
Epoch 6/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7325 - loss: 0.6570
Epoch 7/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6679 - loss: 0.7205
Epoch 8/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7106 - loss: 0.6732
Epoch 9/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6832 - loss: 0.6176
Epoch 10/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6834 - loss: 0.6961
Epoch 11/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7081 -

In [ ]:
resultados

array([0.85964912, 0.78947368, 0.87719298, 0.89473684, 0.8245614 ,
       0.9122807 , 0.9122807 , 0.87719298, 0.8245614 , 0.875     ])

In [ ]:
# Obtivemos um ganho consideravel
resultados.mean()

0.8646929824561405

In [ ]:
# Obtivemos tambem uma melhora no desvio padrao
resultados.std()

0.03841226467630261

## Pratica

In [ ]:
# Aplicação do dropout na rede da pratica anterior

def criar_rede1():
  # Limpa a sessão do tenserflow (libera os recursos, evitando overflow)
  k.clear_session()
  # Cria a rede como visto nas aulas anteriores (4 camadas, 2 ocultas)
  rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    # Nas camadas ocultas, realiza o dropout de 20% dos neuronios
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(units = 8, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')])
  # Parametros do otimizador
  otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue=0.5)
  # Compila tudo e retorna a rede
  rede_neural.compile(optimizer=otimizador, loss='binary_crossentropy', metrics=['binary_accuracy'])
  return rede_neural

# Cria o classificador
rede_neural1 = KerasClassifier(model=criar_rede1, epochs=20, batch_size=70)

In [ ]:
# Realiza a cross validation, com 10 divisões
resultados1 = cross_val_score(estimator=rede_neural1, X=X, y=y, cv=10, scoring='accuracy')

Epoch 1/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - binary_accuracy: 0.4206 - loss: 6.2526
Epoch 2/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.5290 - loss: 1.7083 
Epoch 3/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.5990 - loss: 0.7931 
Epoch 4/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.5751 - loss: 0.7310 
Epoch 5/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.5484 - loss: 0.6848 
Epoch 6/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6064 - loss: 0.6346 
Epoch 7/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6076 - loss: 0.5960 
Epoch 8/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6491 - loss: 0.6507 
Epoch 9/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6081 - loss: 0.5970 
Epoch 10/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6295 - loss: 0.5903 
Epoch 11/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6566 - loss: 0.5871 
Epoch 12/

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
Epoch 1/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - binary_accuracy: 0.5219 - loss: 2.5228
Epoch 2/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6197 - loss: 0.9989 
Epoch 3/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6074 - loss: 0.7185 
Epoch 4/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6541 - loss: 0.6083 
Epoch 5/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6352 - loss: 0.6111 
Epoch 6/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7387 - loss: 0.5195 
Epoch 7/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7285 - loss: 0.4990 
Epoch 8/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7430 - loss: 0.5106 
Epoch 9/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7747 - loss: 0.5172 
Epoch 10/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7177 - loss: 0.4883 
Epoch 11/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accu

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
Epoch 1/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - binary_accuracy: 0.5509 - loss: 2.0228
Epoch 2/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6025 - loss: 0.8260 
Epoch 3/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6135 - loss: 0.6454 
Epoch 4/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.6144 - loss: 0.5738 
Epoch 5/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6167 - loss: 0.5532 
Epoch 6/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6225 - loss: 0.5656 
Epoch 7/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6997 - loss: 0.4964 
Epoch 8/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6467 - loss: 0.5390 
Epoch 9/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6701 - loss: 0.5214 
Epoch 10/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6732 - loss: 0.5155 
Epoch 11/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accu

In [ ]:
resultados1

array([0.71929825, 0.77192982, 0.78947368, 0.85964912, 0.63157895,
       0.84210526, 0.87719298, 0.87719298, 0.59649123, 0.78571429])

In [ ]:
# Piora nos resultados
resultados1.mean()

0.775062656641604

In [ ]:
# Voltando os 16 neuronios, mas ainda modificando epochs e batch_size e o rate de dropout

def criar_rede2():
  # Limpa a sessão do tenserflow (libera os recursos, evitando overflow)
  k.clear_session()
  # Cria a rede como visto nas aulas anteriores (4 camadas, 2 ocultas)
  rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    # Nas camadas ocultas, realiza o dropout de 20% dos neuronios
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dropout(rate=0.25),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dropout(rate=0.25),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')])
  # Parametros do otimizador
  otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue=0.5)
  # Compila tudo e retorna a rede
  rede_neural.compile(optimizer=otimizador, loss='binary_crossentropy', metrics=['binary_accuracy'])
  return rede_neural

# Cria o classificador
rede_neural2 = KerasClassifier(model=criar_rede2, epochs=70, batch_size=23)

In [ ]:
# Realiza a cross validation, com 10 divisões
resultados2 = cross_val_score(estimator=rede_neural2, X=X, y=y, cv=10, scoring='accuracy')

Epoch 1/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.6108 - loss: 1.2489
Epoch 2/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6571 - loss: 0.7466
Epoch 3/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6628 - loss: 0.5676
Epoch 4/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7342 - loss: 0.5819 
Epoch 5/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6817 - loss: 0.5768 
Epoch 6/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7001 - loss: 0.5098 
Epoch 7/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7447 - loss: 0.4857  
Epoch 8/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8003 - loss: 0.4760 
Epoch 9/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7319 - loss: 0.4962 
Epoch 10/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6714 - loss: 0.5593 
Epoch 11/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7404 - lo

In [ ]:
 resultados2

array([0.85964912, 0.85964912, 0.84210526, 0.96491228, 0.87719298,
       0.9122807 , 0.89473684, 0.9122807 , 0.85964912, 0.875     ])

In [ ]:
resultados2.mean()

0.8857456140350877

In [ ]:
# Voltando os 16 neuronios e o rate, mas ainda modificando epochs e batch_size

def criar_rede3():
  # Limpa a sessão do tenserflow (libera os recursos, evitando overflow)
  k.clear_session()
  # Cria a rede como visto nas aulas anteriores (4 camadas, 2 ocultas)
  rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    # Nas camadas ocultas, realiza o dropout de 20% dos neuronios
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')])
  # Parametros do otimizador
  otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue=0.5)
  # Compila tudo e retorna a rede
  rede_neural.compile(optimizer=otimizador, loss='binary_crossentropy', metrics=['binary_accuracy'])
  return rede_neural

# Cria o classificador
rede_neural3 = KerasClassifier(model=criar_rede3, epochs=70, batch_size=23)

In [ ]:
# Realiza a cross validation, com 10 divisões
resultados3 = cross_val_score(estimator=rede_neural3, X=X, y=y, cv=10, scoring='accuracy')

Epoch 1/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.6161 - loss: 1.2350
Epoch 2/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6078 - loss: 0.6842 
Epoch 3/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6159 - loss: 0.5767 
Epoch 4/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6567 - loss: 0.5559
Epoch 5/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7147 - loss: 0.4876 
Epoch 6/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7206 - loss: 0.5697 
Epoch 7/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7856 - loss: 0.4993 
Epoch 8/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7634 - loss: 0.4816 
Epoch 9/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7878 - loss: 0.4565 
Epoch 10/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7618 - loss: 0.4788 
Epoch 11/70
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7695 - lo

In [ ]:
resultados3

array([0.87719298, 0.85964912, 0.89473684, 0.9122807 , 0.84210526,
       0.9122807 , 0.89473684, 0.89473684, 0.85964912, 0.85714286])

In [ ]:
resultados3.mean()

0.8804511278195489

# Tuning dos parametros

In [ ]:
def criar_rede(optimizer, loss, kernel_initializer, activation, neurons):
  # Limpa a sessão do tenserflow (libera os recursos, evitando overflow)
  k.clear_session()
  # Cria a rede como visto nas aulas anteriores (4 camadas, 2 ocultas)
  rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    # Nas camadas ocultas, realiza o dropout de 20% dos neuronios
    tf.keras.layers.Dense(units=neurons, activation=activation, kernel_initializer=kernel_initializer),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(units=neurons, activation=activation, kernel_initializer=kernel_initializer),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(units=1, activation = 'sigmoid')])
  # Compila tudo e retorna a rede
  rede_neural.compile(optimizer=optimizer, loss=loss , metrics=['binary_accuracy'])
  return rede_neural

In [ ]:
rede_neural = KerasClassifier(model=criar_rede)

In [ ]:
# 128 combinações
parametros1 = {
    'batch_size': [10, 30],
    'epochs': [50, 100],
    'model__optimizer': ['adam', 'sgd'],
    'model__loss': ['binary_crossentropy', 'hinge'],
    'model__kernel_initializer': ['random_uniform', 'normal'],
    'model__activation': ['relu', 'tanh'],
    'model__neurons': [16, 8]
}

In [ ]:
# 4 combinações
parametros = {
    'batch_size': [10, 30],
    'epochs': [50],
    'model__optimizer': ['adam'],
    'model__loss': ['binary_crossentropy'],
    'model__kernel_initializer': ['random_uniform', 'normal'],
        'model__activation': ['relu'],
    'model__neurons': [16]
}

In [ ]:
# Gera todas as combinações de parametros acima, e aplica cross validation
grid_search = GridSearchCV(estimator=rede_neural, param_grid=parametros, scoring='accuracy', cv=5)

In [ ]:
# Treina o modelo (a saida ta zoada pq eu cliquei pra executar sem querer)
grid_search = grid_search.fit(X, y)

Epoch 1/50


Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7e464c410430>
Traceback (most recent call last):
  File "/usr/lib/python3.10/weakref.py", line 370, in remove
    def remove(k, selfref=ref(self)):
KeyboardInterrupt: 


Epoch 1/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - binary_accuracy: 0.5772 - loss: 2.0350
Epoch 2/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.5781 - loss: 0.6792
Epoch 3/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.6545 - loss: 0.5577
Epoch 4/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7148 - loss: 0.5529
Epoch 5/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7301 - loss: 0.5042
Epoch 6/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8196 - loss: 0.4345
Epoch 7/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8083 - loss: 0.4279
Epoch 8/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7943 - loss: 0.4145
Epoch 9/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8040 - loss: 0.4056
Epoch 10/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8838 - loss: 0.3410
Epoch 11/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8914 - loss: 0.28

KeyboardInterrupt: 

In [ ]:
# Objeto depois do treino
print(grid_search)

GridSearchCV(cv=5,
             estimator=KerasClassifier(model=<function criar_rede at 0x7e45f3d61a20>),
             param_grid={'batch_size': [10, 30], 'epochs': [50],
                         'model__activation': ['relu'],
                         'model__kernel_initializer': ['random_uniform',
                                                       'normal'],
                         'model__loss': ['binary_crossentropy'],
                         'model__neurons': [16], 'model__optimizer': ['adam']},
             scoring='accuracy')


In [ ]:
# Melhores parametros
grid_search.best_params_

{'batch_size': 10,
 'epochs': 50,
 'model__activation': 'relu',
 'model__kernel_initializer': 'random_uniform',
 'model__loss': 'binary_crossentropy',
 'model__neurons': 16,
 'model__optimizer': 'adam'}

In [ ]:
# Melhor resultado
grid_search.best_score_

0.8927806241266882

## Pratica

In [ ]:
# Eu tentei, mas o colab nao tankou
parametros = {
    'batch_size': [30, 70, 100],
    'epochs': [20, 50],
    'model__optimizer': ['adam'],
    'model__loss': ['binary_crossentropy'],
    'model__kernel_initializer': ['random_uniform'],
        'model__activation': ['relu'],
    'model__neurons': [4, 8, 16]
}

In [ ]:
grid_search = GridSearchCV(estimator=rede_neural, param_grid=parametros, scoring='accuracy', cv=5)

In [ ]:
grid_search = grid_search.fit(X, y)

Streaming output truncated to the last 5000 lines.
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7141 - loss: 0.4958 
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.6920 - loss: 0.5130
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7473 - loss: 0.4919 
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7202 - loss: 0.4726 
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7152 - loss: 0.4858
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7307 - loss: 0.4952
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7161 - loss: 0.4614
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7579 - loss: 0.4378 
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7438 - loss: 0.4900 
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7528 - loss: 0.4439
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0

KeyboardInterrupt: 

# Classificação de somente 1 registro

In [34]:
# Import das classes faltantes
from tensorflow.keras.layers import Dense, InputLayer, Dropout

In [35]:
# Criação da rede neural com os parametros otimos
classificador = Sequential()
classificador.add(InputLayer(shape=(30,)))
classificador.add(Dense(units=16, activation='relu',kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=16, activation='relu',kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=1, activation='sigmoid'))

In [36]:
# Compila com os algoritmos de otimização, erro e metricas
classificador.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [37]:
# treina a rede
classificador.fit(X, y, batch_size=10, epochs=100)

Epoch 1/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - binary_accuracy: 0.5997 - loss: 1.3832
Epoch 2/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - binary_accuracy: 0.6183 - loss: 0.6176
Epoch 3/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7005 - loss: 0.5509
Epoch 4/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7212 - loss: 0.5414
Epoch 5/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7755 - loss: 0.4491
Epoch 6/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8007 - loss: 0.4310
Epoch 7/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - binary_accuracy: 0.8096 - loss: 0.4460
Epoch 8/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - binary_accuracy: 0.8135 - loss: 0.4083
Epoch 9/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8606 - loss: 0.3451
Epoch 10/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8398 - loss: 0.3761
Epoch 11/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8408 -

In [50]:
import numpy as np

In [51]:
# Criação de um novo registro
novo = np.array([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178, 0.20, 0.05,
                 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015, 0.03, 0.007,
                 23.15, 16.64, 178.5, 2018, 0.14, 0.185, 0.84, 158, 0.363]])

In [52]:
novo

array([[1.580e+01, 8.340e+00, 1.180e+02, 9.000e+02, 1.000e-01, 2.600e-01,
        8.000e-02, 1.340e-01, 1.780e-01, 2.000e-01, 5.000e-02, 1.098e+03,
        8.700e-01, 4.500e+03, 1.452e+02, 5.000e-03, 4.000e-02, 5.000e-02,
        1.500e-02, 3.000e-02, 7.000e-03, 2.315e+01, 1.664e+01, 1.785e+02,
        2.018e+03, 1.400e-01, 1.850e-01, 8.400e-01, 1.580e+02, 3.630e-01]])

In [41]:
novo.size

30

In [42]:
# Previsão do novo registro (bateu com a da video aula, infelizmente é maligno)
if classificador.predict(novo) > 0.5:
  print('maligno')
else:
  print('benigno')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
maligno


# Salvar e carregar a rede Neural

In [43]:
classificador.save('classificador_breast.keras')

In [48]:
classificador_novo = tf.keras.models.load_model('/content/classificador_breast.keras')

In [49]:
classificador_novo.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 16)                  │             496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 16)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 16)                  │             272 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 16)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,357 (9.21 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,572 (6.14 KB)

In [53]:
classificador_novo.predict(novo)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step


array([[1.]], dtype=float32)